[tool.poetry]
name = "warehouse"
version = "0.1.0"
description = ""
authors = ["김용환 <k55183@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
